version: "3"

volumes:
  mongo_data:
      driver: local
  mysql_data:
      driver: local

services:
  mongo-db:
    image: "mongo:7"
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=martin
      - MONGO_INITDB_ROOT_PASSWORD=martin

  product-service:
    build:
      context: ../nodejs-microservices-product
    depends_on:
      - mongo-db
    deploy:
      replicas: 3
    environment:
      - MONGO_URL=mongodb://martin:martin@mongo-db:27017

  command-service:
    build:
      context: ../nodejs-microservices-command
    depends_on:
      - mongo-db
    deploy:
      replicas: 2
    environment:
      - MONGO_URL=mongodb://martin:martin@mongo-db:27017
      - PRODUCT_URL=http://product-service:3000/api

  gateway:
    build:
      context: ../nodejs-microservices-gateway
    ports:
      - "4000:4000"
    depends_on:
      - product-service
      - command-service
    environment:
      PRODUCT_HOST: product-service
      COMMAND_HOST: command-service

  keycloak-db:
    image: mysql:8
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: keycloak

  keycloak:
      image: quay.io/keycloak/keycloak:22.0.0
      depends_on:
        - keycloak-db
      environment:
        - KEYCLOAK_USER=keycloak
        - KEYCLOAK_PASSWORD=keycloak
        - KEYCLOAK_ADMIN=root
        - KEYCLOAK_ADMIN_PASSWORD=root

        - KC_DB=mysql
        - KC_DB_URL=jdbc:mysql://keycloak-db:3306/keycloak
        - KC_DB_USERNAME=keycloak
        - KC_DB_PASSWORD=keycloak

        - KC_HEALTH_ENABLED=false
        - KC_FEATURES=token-exchange
        - KC_HOSTNAME=localhost
      command: ['start-dev']
      ports:
        - 8080:8080
        - 443:443
        